---
title: "Visualizations"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---


```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(plotly)
library(viridis)
library(rsconnect)
ecig_data = read.csv("./data/ecig_data.csv")

```


Quit Cigarettes
===================================== 

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r, echo = F, message = F}
years = c("2018", "2017", "2016",  "2015")

selectInput (
  "Year1",
  label = h3("Select Year 1"),
  choices = years,
  selected = "2018"
)

selectInput (
  "Year2",
  label = h3("Select Year 2"),
  choices = years,
  selected = "2017"
)
```

What proportion of kids are actually using electronic cigarettes to quit smoking?  
  
Select two years to compare the distribution of e-cigarette use across intention to quit smoking and year.


Row
-------------------------------------

```{r, echo = F}
renderPlotly ({
  
  yr1 = as.character(input$Year1)
  
  ecig_data %>%
  filter(!age %in% c(9, 10)) %>%
  filter(!is.na(ecigs_past_month)) %>%
  mutate(harm_ecigs = recode(harm_ecigs,
                              "equally addictive" = "equally", "less addictive" = "less", "more addictive" = "more"), 
         ecigs_past_month = factor(ecigs_past_month,
                                   levels = c("0", "1-2", "3-5", "6-9", "10-19", "20-29", "30"),
                                   labels = c("0 days", "1-2 days", "3-5 days", "6-9 days", "10-19 days", "20-29 days", "30 days"))) %>%
  filter(!quit_cig %in% c(NA, "not a smoker")) %>%
  filter(year == input$Year1) %>%
  group_by(quit_cig, ecigs_past_month) %>% 
  summarise(n= n()) %>% 
  mutate(prop = n/sum(n)) %>% 
  plot_ly(
    x = ~quit_cig, y = ~prop,  color = ~ecigs_past_month,
    type = "bar", mode = "markers"
  )  %>%
    layout(
      title = str_c("Distribution of E-Cigarette use by Intentions to Quit Cigarettes in ", yr1),
      xaxis = list(title = "Intention to Quit Cigarettes"),
      yaxis = list(title = "Proportion of Ecig Use",
                   range = c(0, 0.7))
    ) 
})

```


```{r}
renderPlotly ({
  
  yr2 = as.character(input$Year2)
  
   ecig_data %>% 
  filter(!age %in% c(9, 10)) %>%
  filter(!is.na(ecigs_past_month)) %>%
  mutate(harm_ecigs = recode(harm_ecigs,
                              "equally addictive" = "equally", "less addictive" = "less", "more addictive" = "more"), 
         ecigs_past_month = factor(ecigs_past_month,
                                   levels = c("0", "1-2", "3-5", "6-9", "10-19", "20-29", "30"),
                                   labels = c("0 days", "1-2 days", "3-5 days", "6-9 days", "10-19 days", "20-29 days", "30 days"))) %>%
  filter(!quit_cig %in% c(NA, "not a smoker")) %>%
  filter(year == input$Year2) %>%
  group_by(quit_cig, ecigs_past_month) %>% 
  summarise(n= n()) %>% 
  mutate(prop = n/sum(n)) %>% 
  plot_ly(
    x = ~quit_cig, y = ~prop,  color = ~ecigs_past_month,
    type = "bar", mode = "markers"
  )  %>%
    layout(
      title = str_c("Distribution of E-Cigarette use by Intentions to Quit Cigarettes in ", yr2),
      xaxis = list(title = "Intention to Quit Cigarettes"),
      yaxis = list(title = "Proportion of Ecig Use",
                   range = c(0, 0.7))
    ) 
})
```


Smoking Status
===================================== 

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r, echo = F, message = F}
years = c("2018", "2017", "2016",  "2015")

selectInput (
  "Year1",
  label = h3("Select Year 1"),
  choices = years,
  selected = "2018"
)

selectInput (
  "Year2",
  label = h3("Select Year 2"),
  choices = years,
  selected = "2017"
)
```
Are cigarette smokers more likely to use electronic cigarettes?
  
  
Select two years to compare the proportion of e-cigarette use across year, age, and smoking status.


Row
-------------------------------------

```{r, echo = F}
renderPlotly ({
  
  yr1 = as.character(input$Year1)
  
  ecig_data %>%
    filter(!age %in% c(9, 10)) %>%
    filter(year == input$Year1) %>% 
    filter(is.na(age) == FALSE, 
           is.na(try_ecigs) == FALSE,
           is.na(cig_days) == FALSE) %>%
    mutate(current_cig = as.numeric(cig_days != "0")) %>%
    mutate(current_cig = ifelse(current_cig == 0, "NS","S")) %>%
    group_by(age, current_cig) %>%
    mutate(indc = ifelse(try_ecigs == "yes", 1, 0)) %>%
    summarise(y = weighted.mean(indc, as.numeric(weight))) %>%
    pivot_wider(id_cols = age, 
                names_from = current_cig,
                values_from = y) %>%
    ungroup() %>%
    plot_ly(x = ~age, y = ~NS, name = "Non-Smokers",
            type = "scatter", mode = "lines+markers") %>%
    add_trace(y = ~S, name = "Smokers",
              mode = "lines+markers") %>%
    layout(
      title = str_c("Proportion of Ecig Use Within Age and Smoking Status in ", yr1),
      xaxis = list(
        title = "Age",
        domain = c(9:19)
      ),
      yaxis= list(
        title = "Proportion of Ecig Use",
        range = c(0, 1)
      )
    )
    
})
```



```{r, echo = F}
renderPlotly ({
  
  yr2 = as.character(input$Year2)
  
  ecig_data %>%
    filter(!age %in% c(9, 10)) %>%
    filter(year == input$Year2) %>% 
    filter(is.na(age) == FALSE, 
           is.na(try_ecigs) == FALSE,
           is.na(cig_days) == FALSE) %>%
    mutate(current_cig = as.numeric(cig_days != "0")) %>%
    mutate(current_cig = ifelse(current_cig == 0, "NS","S")) %>%
    group_by(age, current_cig) %>%
    mutate(indc = ifelse(try_ecigs == "yes", 1, 0)) %>%
    summarise(y = weighted.mean(indc, as.numeric(weight))) %>%
    pivot_wider(id_cols = age, 
                names_from = current_cig,
                values_from = y) %>%
    ungroup() %>%
    plot_ly(x = ~age, y = ~NS, name = "Non-Smokers",
            type = "scatter", mode = "lines+markers") %>%
    add_trace(y = ~S, name = "Smokers",
              mode = "lines+markers") %>%
    layout(
      title = str_c("Proportion of Ecig Use Within Age and Smoking Status in ", yr2),
      xaxis = list(
        title = "Age",
        domain = c(11:19)
      ),
      yaxis= list(
        title = "Proportion of Ecig Use",
        range = c(0, 1)
      )
    )
    
})

```


Age
===================================== 

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r, echo = F, message = F}
years = c("2018", "2017", "2016",  "2015")

selectInput (
  "Year1",
  label = h3("Select Year 1"),
  choices = years,
  selected = "2018"
)

selectInput (
  "Year2",
  label = h3("Select Year 2"),
  choices = years,
  selected = "2017"
)
```
Has the number of kids who have tried electronic cigarettes risen over time?
  
  
Select two years to compare the proportion of kids who have tried e-cigarettes across year and age.


Row
-------------------------------------

```{r, echo = F}
renderPlotly ({
  
temp = ecig_data %>%
    filter(!age %in% c(9, 10)) %>%
    filter(is.na(age) == FALSE, is.na(sex) == FALSE, is.na(try_ecigs) == FALSE) %>%
    filter(!age %in% c(9,10)) %>%
    group_by(age, year) %>%
    mutate(indc = ifelse(try_ecigs == "yes", 1, 0)) %>%
    summarise(y = weighted.mean(indc, as.numeric(weight))) %>%
    filter(year %in% c(input$Year1, input$Year2)) %>%
    mutate(year = ifelse(year == input$Year1, "year1", "year2")) %>%
    pivot_wider(id_cols = age, names_from = year, values_from = y) %>%
  plot_ly(x = ~age, 
        y = ~year1,
        type = "bar",
        name = input$Year1) %>%
  add_trace(x = ~age,
            y = ~year2,
            type = "bar",
            width = 0.3,
            name = input$Year2) %>%
  layout(barmode = "overlay",
         title = "Proportion of Kids who Have Tried Electronic Cigarettes",
         xaxis = list(title = "Age"),
         yaxis = list(title = "Proportion Tried E-cigarettes")
  )

})

```









